# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  init:
    name: init
    runs-on: ubuntu-22.04
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
    steps:
      - uses: actions/checkout@v3.1.0
      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1

  test_push:
    name: Test on push
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' && github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Node.js tests
        run: npm run test

  test_bun:
    name: Test with Bun
    needs: init
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1.3.1
        with:
          version: '>=0.1.1'

      - name: Run Bun tests
        run: bun run test

  test_pr:
    if: ${{ needs.init.outputs.skip == 'false' && github.event_name == 'pull_request' }}
    needs: init
    name: Test PR (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        node-version: [ 14, 16, 18 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - if: matrix.os == 'windows-2022'
        run: npm i -g npm@latest --force

      - name: Run tests
        timeout-minutes: 2
        run: npm run test

  release:
    name: Release
    # https://github.community/t/trigger-job-on-tag-push-only/18076
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test_push, test_bun]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run tests
        run: npm run test:cov

      - name: Docs
        run: npm run docs

      - name: Codeclimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'mailbox@antongolub.ru'
          GIT_COMMITTER_EMAIL: 'mailbox@antongolub.ru'
          GIT_AUTHOR_NAME: '@antongolub'
          GIT_COMMITTER_NAME: '@antongolub'
        run: npm_config_yes=true npx -p @qiwi/semrel-toolkit semrel
